- obs space:
    name: sst___OBS_PLAT__
    distribution: *obs_distribution
    obsdatain:  {obsfile: __OBS_IN_FILE__}
    obsdataout: {obsfile: __OBS_OUT_DIR__/sst___OBS_PLAT__.nc}
    simulated variables: [sea_surface_temperature]
  obs operator:
    name: Identity
  obs error:
    covariance model: diagonal
  obs localization: # note, this is only used for LETKF
    localization method: Rossby
    search method: kd_tree
    base value: 50.0e3
    rossby mult: 1.5
    min grid mult: 2.0
    min value: 50.0e3
    max value: 200.0e3
  obs filters:
  - *obs_land_mask
  - filter: Bounds Check
    minvalue: -2.0
    maxvalue: 36.0
  - filter: Background Check
    threshold: 1.0
  - filter: Domain Check
    where:
    - variable: {name: sea_surface_temperature@ObsError}
      minvalue: 0.001

  ## Gaussian_Thinning is having problems with the LETKF, try again alter
  # - filter: Gaussian_Thinning
  #   horizontal_mesh:   25.0 #km
